version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
branches:
  only:
  - master
  - appveyor_test
environment:
  WHEEL_DIR: C:\kivy_wheels
  COMPILER: mingw
  KIVY_BUILD_DIR: C:\kivy_build
  KIVY_BUILD_CACHE: C:\kivy_build_cache2
  KEY_WITH_NO_TEETH:
    secure: 7cS7xjpCL/VH5jIIGSf13camkiu1enMh5hO0UsBgmRlBXyKk3t/7HB79ofyJKgDb
  SERVER_IP: 159.203.106.198
  MSYSTEM: MINGW64
  CHERE_INVOKING: 1
  UPLOAD_DEV: 1
  matrix:
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
    UPLOAD_DEV: 0
  - PACKAGE_TARGET: sdl2
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
    UPLOAD_DEV: 0
  - PACKAGE_TARGET: sdl2
    PYVER: 37
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 37
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 37
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 37
    BITTNESS: 86
    COMPILER: msvc
    UPLOAD_DEV: 0
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
    UPLOAD_DEV: 0
  - PACKAGE_TARGET: sdl2
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
    UPLOAD_DEV: 0
  - PACKAGE_TARGET: sdl2
    PYVER: 37
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 37
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 37
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 37
    BITTNESS: 64
    COMPILER: msvc
    UPLOAD_DEV: 0
cache: C:\kivy_build_cache2
build_script:
- nuget install secure-file -ExcludeVersion
- ps: >-
    function Check-Error
    {
      param([int]$SuccessVal = 0)
      if ($SuccessVal -ne $LastExitCode) {
        throw "Failed with exit code $LastExitCode"
      }
    }


    $env:SSL_CERT_FILE="C:\projects\kivy-sdk-packager\win\DST Root CA X3.pem"

    cd C:\projects\kivy-sdk-packager


    mkdir "$env:KIVY_BUILD_DIR"

    mkdir "$env:WHEEL_DIR"

    if (!(Test-Path "$env:KIVY_BUILD_CACHE")) {
      mkdir "$env:KIVY_BUILD_CACHE"
    }


    if ($env:BITTNESS -eq "64") {
      $PYTHON_ROOT = "C:\Python$env:PYVER-x64"
      $WHELL_BITNESS = "win_amd64"
    } else {
      $PYTHON_ROOT = "C:\Python$env:PYVER"
      $WHELL_BITNESS = "win32"
    }

    $env:PATH = "$PYTHON_ROOT;$PYTHON_ROOT\Scripts;$env:PATH"



    $WHEEL_VERSION = python -c "import win.$env:PACKAGE_TARGET;print(win.$env:PACKAGE_TARGET.__version__)"

    Check-Error

    $WHEEL_BIN = "kivy.deps.$env:PACKAGE_TARGET-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"

    $WHEEL_DEV = "kivy.deps.$env:PACKAGE_TARGET`_dev-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"


    C:\Python35-x64\Scripts\pip.exe install requests

    Check-Error

    $ALREADY_EXISTS = C:\Python35-x64\python.exe -c "import requests; print(1 if requests.head('https://kivy.org/downloads/appveyor/deps/$env:PACKAGE_TARGET/$WHEEL_BIN').status_code == 200 else '')"

    Check-Error

    if ($ALREADY_EXISTS -eq "1" -and $env:UPLOAD_DEV -eq "1") {
      $ALREADY_EXISTS = C:\Python35-x64\python.exe -c "import requests; print(1 if requests.head('https://kivy.org/downloads/appveyor/deps/$env:PACKAGE_TARGET`_dev/$WHEEL_DEV').status_code == 200 else '')"
      Check-Error
    }

    echo "Already exists=$ALREADY_EXISTS : $WHEEL_BIN, $WHEEL_DEV"


    if ($ALREADY_EXISTS -ne "1") {
      python -m pip install pip wheel setuptools --upgrade
      Check-Error
      if ($env:COMPILER -eq "mingw") {
        pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
        Check-Error
      }

      echo "Executing win.$env:PACKAGE_TARGET build_path $env:KIVY_BUILD_DIR arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output $env:WHEEL_DIR cache $env:KIVY_BUILD_CACHE compiler $env:COMPILER"
      python -m win.$env:PACKAGE_TARGET build_path "$env:KIVY_BUILD_DIR" arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output "$env:WHEEL_DIR" cache "$env:KIVY_BUILD_CACHE" compiler "$env:COMPILER"
      Check-Error

      secure-file\tools\secure-file -decrypt C:\projects\kivy-sdk-packager\ci\id_rsa.enc -secret "$env:KEY_WITH_NO_TEETH"
      Check-Error

      if ($env:UPLOAD_DEV -eq "1") {
        C:\msys64\usr\bin\bash --login -c "/c/projects/kivy-sdk-packager/ci/appveyor_server_upload.sh $env:SERVER_IP '$env:WHEEL_DIR' kivy.deps.$env:PACKAGE_TARGET`_dev-* appveyor/deps/$env:PACKAGE_TARGET`_dev/"
        Check-Error
      }
      C:\msys64\usr\bin\bash --login -c "/c/projects/kivy-sdk-packager/ci/appveyor_server_upload.sh $env:SERVER_IP '$env:WHEEL_DIR' kivy.deps.$env:PACKAGE_TARGET-* appveyor/deps/$env:PACKAGE_TARGET/"
      Check-Error
    }
