name: SDL2 wheels

on:
  push:
    branches:
      - master
      - windows_ci
    paths:
      - 'win/sdl2.py'
      - '.github/workflows/windows_sdl2_wheels.yml'
      - 'ci/windows_ci.ps1'

env:
  SERVER_IP: '159.203.106.198'
  KIVY_BUILD_DIR: kivy_build
  KIVY_BUILD_CACHE: kivy_build_cache
  PACKAGE_TARGET: sdl2
  PYTHONPATH: .

jobs:
  prepare_cache:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ['x64', 'x86']
    env:
      PACKAGE_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache deps
        id: cache
        uses: actions/cache@v2
        with:
          path: kivy_build_cache
          key: cache-packages-sdl2-${{ matrix.arch }}-${{ hashFiles('win/sdl2.py') }}
      - name: Prepare Environment
        run: |
          . .\ci\windows_ci.ps1
          Prepre-env
      - name: Download Dependencies
        run: |
          . .\ci\windows_ci.ps1
          Download-Packages
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Prepare HarfBuzz/sdl_ttf
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          . .\ci\windows_ci.ps1
          Prepare-ttf -arch ${{ matrix.arch }}

  windows_wheels:
    runs-on: windows-latest
    needs: prepare_cache
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.6', '3.7', '3.8', '3.9' ]
        arch: ['x64', 'x86']
    env:
      PACKAGE_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: kivy_build_cache
        key: cache-packages-sdl2-${{ matrix.arch }}-${{ hashFiles('win/sdl2.py') }}
    - name: Prepare Environment
      run: |
        . .\ci\windows_ci.ps1
        Prepre-env
    - name: Build package
      run: |
        . .\ci\windows_ci.ps1
        Create-Packages
    - name: Upload wheels as artifact
      uses: actions/upload-artifact@master
      with:
        name: sdl2_wheels
        path: dist
    - name: Install MSYS2
      if: contains(github.event.head_commit.message, '[publish sdl2 win]')
      run: choco install msys2
    - name: Upload wheels to server
      if: contains(github.event.head_commit.message, '[publish sdl2 win]')
      env:
        UBUNTU_UPLOAD_KEY: ${{ secrets.UBUNTU_UPLOAD_KEY }}
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
      run: |
        . .\ci\windows_ci.ps1
        Upload-windows-wheels-to-server -ip "$env:SERVER_IP"
    - name: Publish to PyPI
      if: contains(github.event.head_commit.message, '[publish sdl2 win]')
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        twine upload --non-interactive dist/*
    - name: Test package
      run: |
        . .\ci\windows_ci.ps1
        Test-kivy
